spring:
 mvc:
   view:
     prefix: /webapp/view/
     suffix: .jsp
 jpa:
  database: postgresql
  show-sql: true
  generate-ddl: true
  hibernate:
    ddl-auto: update
  properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
      jdbc:
      lob:
      non_contextual_creation:
          true
 datasource:
     url: jdbc:postgresql://localhost:5432/bank
     username: postgres
     password: 239
     driver-class-name: org.postgresql.Driver
